# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Touch' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SDWebImage'
  pod 'Firebase/Database'

  # Pods for Touch

end
